//
//  Bindings.swift
//  Schema
//
//  Created by James Clark on 12/12/17.
//

import Foundation


// -- Shop Service (v1) -- //

// Ping
public typealias Bloombox_Schema_Services_Shop_V1_Ping_Request = Bloombox_Schema_Services_Shop_V1_Ping.Request
public typealias Bloombox_Schema_Services_Shop_V1_Ping_Response = Bloombox_Schema_Services_Shop_V1_Ping.Response

// ShopInfo
public typealias Bloombox_Schema_Services_Shop_V1_ShopInfo_Request = Bloombox_Schema_Services_Shop_V1_ShopInfo.Request
public typealias Bloombox_Schema_Services_Shop_V1_ShopInfo_Response = Bloombox_Schema_Services_Shop_V1_ShopInfo.Response

// Zipcheck
public typealias Bloombox_Schema_Services_Shop_V1_CheckZipcode_Request = Bloombox_Schema_Services_Shop_V1_CheckZipcode.Request
public typealias Bloombox_Schema_Services_Shop_V1_CheckZipcode_Response = Bloombox_Schema_Services_Shop_V1_CheckZipcode.Response

// VerifyMember
public typealias Bloombox_Schema_Services_Shop_V1_VerifyMember_Request = Bloombox_Schema_Services_Shop_V1_VerifyMember.Request
public typealias Bloombox_Schema_Services_Shop_V1_VerifyMember_Response = Bloombox_Schema_Services_Shop_V1_VerifyMember.Response

// EnrollMember
public typealias Bloombox_Schema_Services_Shop_V1_EnrollMember_Request = Bloombox_Schema_Services_Shop_V1_EnrollMember.Request
public typealias Bloombox_Schema_Services_Shop_V1_EnrollMember_Response = Bloombox_Schema_Services_Shop_V1_EnrollMember.Response

// GetOrder
public typealias Bloombox_Schema_Services_Shop_V1_GetOrder_Request = Bloombox_Schema_Services_Shop_V1_GetOrder.Request
public typealias Bloombox_Schema_Services_Shop_V1_GetOrder_Response = Bloombox_Schema_Services_Shop_V1_GetOrder.Response

// GetOrder
public typealias Bloombox_Schema_Services_Shop_V1_SubmitOrder_Request = Bloombox_Schema_Services_Shop_V1_SubmitOrder.Request
public typealias Bloombox_Schema_Services_Shop_V1_SubmitOrder_Response = Bloombox_Schema_Services_Shop_V1_SubmitOrder.Response


// -- Telemetry Service (v1beta3) -- //

// Generic Telemetry
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_TelemetryPing_Request = Bloombox_Schema_Services_Telemetry_V1beta3_TelemetryPing.Request
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_TelemetryPing_Response = Bloombox_Schema_Services_Telemetry_V1beta3_TelemetryPing.Response
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_Event_Request = Bloombox_Schema_Services_Telemetry_V1beta3_Event.Request
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_Event_Batch = Bloombox_Schema_Services_Telemetry_V1beta3_Event.Batch
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_Event_BatchRequest = Bloombox_Schema_Services_Telemetry_V1beta3_Event.BatchRequest

// Commercial Telemetry
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent_Impression = Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent.Impression
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent_View = Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent.View
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent_Action = Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent.Action

// Identity Telemetry
public typealias Bloombox_Schema_Services_Telemetry_V1beta3_IdentityEvent_Action = Bloombox_Schema_Services_Telemetry_V1beta3_IdentityEvent.Action

// Event Analytics
public typealias EventTelemetryService = Bloombox_Schema_Services_Telemetry_V1Beta3_EventTelemetryService
public typealias TelemetryPing = Bloombox_Schema_Services_Telemetry_V1beta3_TelemetryPing
public typealias TelemetryEvent = Bloombox_Schema_Services_Telemetry_V1beta3_Event
public typealias TelemetryException = Bloombox_Schema_Services_Telemetry_V1beta3_Exception
public typealias EventTelemetryClientError =  Bloombox_Schema_Services_Telemetry_V1Beta3_EventTelemetryClientError
public typealias Services_Telemetry_V1beta2_Event_Request = Bloombox_Schema_Services_Telemetry_V1beta3_Event.Request
public typealias Services_Telemetry_V1beta2_Event_Batch = Bloombox_Schema_Services_Telemetry_V1beta3_Event.Batch
public typealias Services_Telemetry_V1beta2_Event_BatchRequest = Bloombox_Schema_Services_Telemetry_V1beta3_Event.BatchRequest

// Commercial Analytics
public typealias Bloombox_Schema_Services_Telemetry_V1beta2_CommercialEvent_View = Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent.View
public typealias Bloombox_Schema_Services_Telemetry_V1beta2_CommercialEvent_Action = Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent.Action
public typealias Bloombox_Schema_Services_Telemetry_V1beta2_CommercialEvent_Impression = Bloombox_Schema_Services_Telemetry_V1beta3_CommercialEvent.Impression

// Commercial Analytics
public typealias Bloombox_Schema_Services_Telemetry_V1beta2_IdentityEvent_Action = Bloombox_Schema_Services_Telemetry_V1beta3_IdentityEvent.Action


// -- Checkin Service (v1beta1) -- //

public typealias Bloombox_Schema_Services_Checkin_V1beta1_Ping_Request = Bloombox_Schema_Services_Checkin_V1beta1_Ping.Request
public typealias Bloombox_Schema_Services_Checkin_V1beta1_Ping_Response = Bloombox_Schema_Services_Checkin_V1beta1_Ping.Response
public typealias Bloombox_Schema_Services_Checkin_V1beta1_IDCheckin_Request = Bloombox_Schema_Services_Checkin_V1beta1_IDCheckin.Request
public typealias Bloombox_Schema_Services_Checkin_V1beta1_CardCheckin_Request = Bloombox_Schema_Services_Checkin_V1beta1_CardCheckin.Request


// -- Devices Service (v1beta1) -- //

public typealias Bloombox_Schema_Services_Devices_V1beta1_Ping_Request = Bloombox_Schema_Services_Devices_V1beta1_Ping.Request
public typealias Bloombox_Schema_Services_Devices_V1beta1_Ping_Response = Bloombox_Schema_Services_Devices_V1beta1_Ping.Response
public typealias Bloombox_Schema_Services_Devices_V1beta1_Activation_Request = Bloombox_Schema_Services_Devices_V1beta1_Activation.Request
public typealias Bloombox_Schema_Services_Devices_V1beta1_Activation_Response = Bloombox_Schema_Services_Devices_V1beta1_Activation.Response


// -- Menu Service (v1beta1) -- //

public typealias Bloombox_Schema_Services_Menu_V1beta1_Ping_Request = Bloombox_Schema_Services_Menu_V1beta1_Ping.Request
public typealias Bloombox_Schema_Services_Menu_V1beta1_Ping_Response = Bloombox_Schema_Services_Menu_V1beta1_Ping.Response
public typealias Bloombox_Schema_Services_Menu_V1beta1_GetMenu_Request = Bloombox_Schema_Services_Menu_V1beta1_GetMenu.Request
public typealias Bloombox_Schema_Services_Menu_V1beta1_GetMenu_Response = Bloombox_Schema_Services_Menu_V1beta1_GetMenu.Response

