// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: commerce/Customer.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

///*
/// Specifies the notion of a 'customer,' which is a person who is completing a purchase transaction, has completed a
/// purchase transaction in the past, or intends to commit a purchase transaction in the future.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Customer identity.
public struct Opencannabis_Commerce_Customer {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Person attached to this customer.
  public var person: Opencannabis_Person_Person {
    get {return _storage._person ?? Opencannabis_Person_Person()}
    set {_uniqueStorage()._person = newValue}
  }
  /// Returns true if `person` has been explicitly set.
  public var hasPerson: Bool {return _storage._person != nil}
  /// Clears the value of `person`. Subsequent reads from it will return its default value.
  public mutating func clearPerson() {_uniqueStorage()._person = nil}

  /// Partner-scoped foreign system ID.
  public var foreignID: String {
    get {return _storage._foreignID}
    set {_uniqueStorage()._foreignID = newValue}
  }

  /// Resolved subject user key.
  public var userKey: String {
    get {return _storage._userKey}
    set {_uniqueStorage()._userKey = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "opencannabis.commerce"

extension Opencannabis_Commerce_Customer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Customer"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "person"),
    2: .standard(proto: "foreign_id"),
    3: .standard(proto: "user_key"),
  ]

  fileprivate class _StorageClass {
    var _person: Opencannabis_Person_Person? = nil
    var _foreignID: String = String()
    var _userKey: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _person = source._person
      _foreignID = source._foreignID
      _userKey = source._userKey
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._person)
        case 2: try decoder.decodeSingularStringField(value: &_storage._foreignID)
        case 3: try decoder.decodeSingularStringField(value: &_storage._userKey)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._person {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._foreignID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._foreignID, fieldNumber: 2)
      }
      if !_storage._userKey.isEmpty {
        try visitor.visitSingularStringField(value: _storage._userKey, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Opencannabis_Commerce_Customer, rhs: Opencannabis_Commerce_Customer) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._person != rhs_storage._person {return false}
        if _storage._foreignID != rhs_storage._foreignID {return false}
        if _storage._userKey != rhs_storage._userKey {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
