// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: security/IdentityToken.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

///*
/// Specifies the notion of a user identity token, which is used to specify/transmit/emit user authorization assertion
/// materials to frontends (in particular, web).

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Enumerates identity token issuers, or authorizing IdPs (Identity Providers). Internal authorization refers to systems
/// internal to Bloombox, where a system account is authorizing some resource. Otherwise, Firebase is the main auth
/// mechanism for end-users.
public enum Bloombox_Schema_Security_IdentityTokenIssuer: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// Internal, Bloombox-system account authentication.
  case `internal` // = 0

  /// Firebase end-user authentication.
  case firebase // = 1

  /// Auth0-powered authentication.
  case auth0 // = 2

  /// GSuite-powered authentication.
  case google // = 3

  /// Second-party domain authentication, perhaps via SAML or other SSO technologies.
  case domain // = 4

  /// External IDP-powered authentication.
  case external // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .internal
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .internal
    case 1: self = .firebase
    case 2: self = .auth0
    case 3: self = .google
    case 4: self = .domain
    case 5: self = .external
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .internal: return 0
    case .firebase: return 1
    case .auth0: return 2
    case .google: return 3
    case .domain: return 4
    case .external: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

}

/// Specifies an individual token asserting the identity of a user. An identity token does not make any claim related to
/// authorization, only identity.
public struct Bloombox_Schema_Security_IdentityToken: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".IdentityToken"

  /// ID for the subject user.
  public var uid: String = String()

  /// Encoded JWT identity token.
  public var encoded: String = String()

  /// Token issuer, or authorizing IdP (Identity Provider).
  public var issuer: Bloombox_Schema_Security_IdentityTokenIssuer = .internal

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.uid)
      case 2: try decoder.decodeSingularStringField(value: &self.encoded)
      case 3: try decoder.decodeSingularEnumField(value: &self.issuer)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.uid.isEmpty {
      try visitor.visitSingularStringField(value: self.uid, fieldNumber: 1)
    }
    if !self.encoded.isEmpty {
      try visitor.visitSingularStringField(value: self.encoded, fieldNumber: 2)
    }
    if self.issuer != .internal {
      try visitor.visitSingularEnumField(value: self.issuer, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "bloombox.schema.security"

extension Bloombox_Schema_Security_IdentityTokenIssuer: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "INTERNAL"),
    1: .same(proto: "FIREBASE"),
    2: .same(proto: "AUTH0"),
    3: .same(proto: "GOOGLE"),
    4: .same(proto: "DOMAIN"),
    5: .same(proto: "EXTERNAL"),
  ]
}

extension Bloombox_Schema_Security_IdentityToken: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "uid"),
    2: .same(proto: "encoded"),
    3: .same(proto: "issuer"),
  ]

  public func _protobuf_generated_isEqualTo(other: Bloombox_Schema_Security_IdentityToken) -> Bool {
    if self.uid != other.uid {return false}
    if self.encoded != other.encoded {return false}
    if self.issuer != other.issuer {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
