
project 'Example.xcodeproj/'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:bloombox/specs.git'

platform :ios, '12.0'
inhibit_all_warnings!

target 'Example' do
  use_frameworks!

  pod 'OpenCannabis', :git => 'https://github.com/bloombox/swift.git'
  pod 'Bloombox', :git => 'https://github.com/bloombox/swift.git'
end

