engines:
  duplication:
    enabled: true
  tailor:
    enabled: true
    include:
      - "Sources/Client"
    exclude:
      - "Sources/Schema"
    except:
      - function-whitespace
      - upper-camel-case
      - constant-k-prefix
  fixme:
    enabled: true
ratings:
  paths:
  - "Sources/Client/**.swift"
exclude_paths:
- "Sources/Schema/**.swift"
