clean: true
output: docs
author: Bloombox
author_url: https://bloombox.io
module: Client
module_version: 0.0.1
copyright: "Copyright (&copy;) 2017, Bloombox, LLC. Released under the Apache License v2.0."
readme: "README.md"
root_url: https://bloombox.github.io/Swift/
github_url: https://github.com/bloombox/Swift
github_file_prefix: https://github.com/bloombox/Swift/tree/master
min_acl: public
theme: apple
xcodebuild_arguments:
  - "-target"
  - "Client"
source_directory: .

