os: osx
osx_image: xcode11
env:
  global:
    - CODECOV_TOKEN=5f05c93b-cde4-421b-b1a7-7da0b91d9c67
language: swift
xcode_project: Bloombox.xcodeproj
xcode_scheme: Client
git:
  submodules: false
before_script:
  - rm -fr .build && swift package resolve && swift package generate-xcodeproj
before_install: rvm use $RVM_RUBY_VERSION
install:
  - bundle install --without=documentation --path ../travis_bundle_dir
script: fastlane testsuite
after_script:
  - bash <(curl -s https://codecov.io/bash) -f ./coverage-out/cobertura.xml -X xcode -J 'Bloombox'

