os: osx
osx_image: xcode9.2
env:
  global:
    - CC_TEST_REPORTER_ID=a6aef1a4ab6ca369c8f1845a8ee3697f0841a42a81db527b3948a595fb2b9c22
language: swift
xcode_project: BloomboxClient.xcodeproj
xcode_scheme: BloomboxClient
git:
  submodules: false
cache:
  directories:
    - ./.build
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - swift package generate-xcodeproj
  - make
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

