
ignore:
  - ".build/*"
  - ".build/**/*"
  - "Sources/Schema/*"
  - "Sources/Schema/**/*"
  - "Sources/Services/*"
  - "Sources/Services/**/*"
  - "Tests/**/*"
  - "Pods/**/*"
  - "Example/**/*"

coverage:
  range: 50..100
  round: down
  precision: 2

